### ISSUE TITLE
timeout of 240000ms exceeded

### ISSUE THREAD

**Issue by fungaegis** [appium/appium-docker-android#136]
Can someone help me? 
1. When I execute the 'send' operation, there will be a timeout "an unknown server side error occurred while processing the command. Original error: could not proxy command to the remote server. Original error: timeout of 240000ms exceeded", " https://github.com/appium/appium/issues/14998 I don't know how to solve it. I don't know how to configure this container
2. The other is that I run on the app written by "react native". The speed of element positioning is very slow. An operation needs 40s +. It's not because I use XPath, even if I use uiautomator2
```log
2021-03-24 11:51:08:794 [WD Proxy] Got response with status 200: {"sessionId":"0c83fe8d-1167-4d43-ad99-0398ed1d70ef","value":null}
2021-03-24 11:51:08:795 [W3C (ff2545a6)] Responding to client with driver.click() result: null
2021-03-24 11:51:08:797 [HTTP] <-- POST /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element/1f53ab4e-d6ff-4ce8-a3cb-d588738ea7c3/click 200 30299 ms - 14
2021-03-24 11:51:08:838 [HTTP] --> POST /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element
2021-03-24 11:51:08:838 [HTTP] {"using":"xpath","value":"//android.widget.EditText[@content-desc=\"label-identity-pan-number\"]"}
2021-03-24 11:51:08:839 [W3C (ff2545a6)] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.EditText[@content-desc=\"label-identity-pan-number\"]","ff2545a6-108d-4427-b595-9bd02a835aa9"]
2021-03-24 11:51:08:840 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2021-03-24 11:51:08:840 [BaseDriver] Waiting up to 0 ms for condition
2021-03-24 11:51:08:841 [WD Proxy] Matched '/element' to command name 'findElement'
2021-03-24 11:51:08:841 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8200/wd/hub/session/0c83fe8d-1167-4d43-ad99-0398ed1d70ef/element] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@content-desc=\"label-identity-pan-number\"]","context":"","multiple":false}

2021-03-24 11:51:19:331 [WD Proxy] Got response with status 200: {"sessionId":"0c83fe8d-1167-4d43-ad99-0398ed1d70ef","value":{"ELEMENT":"d2f67b0b-14de-4a3f-9670-f7746ef15b28","element-6066-11e4-a52e-4f735466cecf":"d2f67b0b-14de-4a3f-9670-f7746ef15b28"}}
2021-03-24 11:51:19:332 [W3C (ff2545a6)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"d2f67b0b-14de-4a3f-9670-f7746ef15b28","ELEMENT":"d2f67b0b-14de-4a3f-9670-f7746ef15b28"}
2021-03-24 11:51:19:334 [HTTP] <-- POST /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element 200 10495 ms - 137
2021-03-24 11:51:19:340 [HTTP] --> GET /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/displayed
2021-03-24 11:51:19:340 [HTTP] {}
2021-03-24 11:51:19:341 [W3C (ff2545a6)] Calling AppiumDriver.elementDisplayed() with args: ["d2f67b0b-14de-4a3f-9670-f7746ef15b28","ff2545a6-108d-4427-b595-9bd02a835aa9"]
2021-03-24 11:51:19:342 [WD Proxy] Matched '/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/attribute/displayed' to command name 'getAttribute'
2021-03-24 11:51:19:342 [WD Proxy] Proxying [GET /element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/attribute/displayed] to [GET http://127.0.0.1:8200/wd/hub/session/0c83fe8d-1167-4d43-ad99-0398ed1d70ef/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/attribute/displayed] with no body

2021-03-24 11:51:39:518 [WD Proxy] Got response with status 200: {"sessionId":"0c83fe8d-1167-4d43-ad99-0398ed1d70ef","value":"true"}
2021-03-24 11:51:39:518 [W3C (ff2545a6)] Responding to client with driver.elementDisplayed() result: true
2021-03-24 11:51:39:519 [HTTP] <-- GET /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/displayed 200 20179 ms - 14
2021-03-24 11:51:39:523 [HTTP] --> POST /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/value
2021-03-24 11:51:39:523 [HTTP] {"text":"CNKYD5118J","value":["C","N","K","Y","D","5","1","1","8","J"],"id":"d2f67b0b-14de-4a3f-9670-f7746ef15b28"}
2021-03-24 11:51:39:524 [W3C (ff2545a6)] Calling AppiumDriver.setValue() with args: [["C","N","K","Y","D","5","1","1","8","J"],"d2f67b0b-14de-4a3f-9670-f7746ef15b28","ff2545a6-108d-4427-b595-9bd02a835aa9"]
2021-03-24 11:51:39:524 [WD Proxy] Matched '/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/value' to command name 'setValue'
2021-03-24 11:51:39:524 [Protocol Converter] Added 'value' property ["C","N","K","Y","D","5","1","1","8","J"] to 'setValue' request body
2021-03-24 11:51:39:524 [WD Proxy] Proxying [POST /element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/value] to [POST http://127.0.0.1:8200/wd/hub/session/0c83fe8d-1167-4d43-ad99-0398ed1d70ef/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/value] with body: {"elementId":"d2f67b0b-14de-4a3f-9670-f7746ef15b28","text":"CNKYD5118J","replace":false,"value":["C","N","K","Y","D","5","1","1","8","J"]}

2021-03-24 11:52:39:529 [WD Proxy] Error: timeout of 240000ms exceeded
2021-03-24 11:52:39:530 [WD Proxy]     at createError (/usr/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
2021-03-24 11:52:39:530 [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
2021-03-24 11:52:39:530 [WD Proxy]     at Object.onceWrapper (events.js:421:26)
2021-03-24 11:52:39:530 [WD Proxy]     at RedirectableRequest.emit (events.js:314:20)
2021-03-24 11:52:39:531 [WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/lib/node_modules/appium/node_modules/follow-redirects/index.js:13:24)
2021-03-24 11:52:39:531 [WD Proxy]     at ClientRequest.emit (events.js:314:20)
2021-03-24 11:52:39:531 [WD Proxy]     at Socket.emitRequestTimeout (_http_client.js:715:9)
2021-03-24 11:52:39:531 [WD Proxy]     at Object.onceWrapper (events.js:420:28)
2021-03-24 11:52:39:531 [WD Proxy]     at Socket.emit (events.js:326:22)
2021-03-24 11:52:39:532 [WD Proxy]     at Socket._onTimeout (net.js:483:8)
2021-03-24 11:52:39:532 [WD Proxy]     at listOnTimeout (internal/timers.js:554:17)
2021-03-24 11:52:39:532 [WD Proxy]     at processTimers (internal/timers.js:497:7)
2021-03-24 11:52:39:534 [W3C (ff2545a6)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
2021-03-24 11:52:39:536 [W3C (ff2545a6)]     at UIA2Proxy.command (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
2021-03-24 11:52:39:536 [W3C (ff2545a6)]     at runMicrotasks (<anonymous>)
2021-03-24 11:52:39:536 [W3C (ff2545a6)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-24 11:52:39:538 [HTTP] <-- POST /wd/hub/session/ff2545a6-108d-4427-b595-9bd02a835aa9/element/d2f67b0b-14de-4a3f-9670-f7746ef15b28/value 500 60014 ms - 657
```

I'm using v1.20.2
```log
2021-03-24 11:51:08:470 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2021-03-24 11:51:08:471 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.20.2"}}
2021-03-24 11:51:08:472 [HTTP] <-- GET /wd/hub/status 200 2 ms - 68
```
I adjusted "UI Automator 2 server readtimeout" to 500000, but it still can't work normally. I checked the log and found that the default timeout should be 240000 MS, but an error was thrown at 60000 Ms. if I set the time to be more than 60000 MS, it will not take effect. If it is less than 60000 MS, it will take effect normally, My program has no errors. The version number of my local service is also v1.20.2
```log
2021-03-25 04:05:57:343 [HTTP] --> POST /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/element/5264a6b5-7551-4c60-ae6c-6707a8256da6/value
2021-03-25 04:05:57:343 [HTTP] {"text":"LHJLA6972O","value":["L","H","J","L","A","6","9","7","2","O"],"id":"5264a6b5-7551-4c60-ae6c-6707a8256da6"}
2021-03-25 04:05:57:344 [W3C (7f4121c1)] Calling AppiumDriver.setValue() with args: [["L","H","J","L","A","6","9","7","2","O"],"5264a6b5-7551-4c60-ae6c-6707a8256da6","7f4121c1-5a08-476f-9407-8b36d19d4731"]
2021-03-25 04:05:57:346 [WD Proxy] Matched '/element/5264a6b5-7551-4c60-ae6c-6707a8256da6/value' to command name 'setValue'
2021-03-25 04:05:57:346 [Protocol Converter] Added 'value' property ["L","H","J","L","A","6","9","7","2","O"] to 'setValue' request body
2021-03-25 04:05:57:346 [WD Proxy] Proxying [POST /element/5264a6b5-7551-4c60-ae6c-6707a8256da6/value] to [POST http://127.0.0.1:8200/wd/hub/session/0fb5edbf-1fe4-4549-91b7-364bbc14aa5c/element/5264a6b5-7551-4c60-ae6c-6707a8256da6/value] with body: {"elementId":"5264a6b5-7551-4c60-ae6c-6707a8256da6","text":"LHJLA6972O","replace":false,"value":["L","H","J","L","A","6","9","7","2","O"]}

2021-03-25 04:06:57:351 [WD Proxy] Error: timeout of 480000ms exceeded
2021-03-25 04:06:57:351 [WD Proxy]     at createError (/usr/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
2021-03-25 04:06:57:352 [WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
2021-03-25 04:06:57:352 [WD Proxy]     at Object.onceWrapper (events.js:421:26)
2021-03-25 04:06:57:352 [WD Proxy]     at RedirectableRequest.emit (events.js:314:20)
2021-03-25 04:06:57:352 [WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/lib/node_modules/appium/node_modules/follow-redirects/index.js:13:24)
2021-03-25 04:06:57:353 [WD Proxy]     at ClientRequest.emit (events.js:314:20)
2021-03-25 04:06:57:353 [WD Proxy]     at Socket.emitRequestTimeout (_http_client.js:715:9)
2021-03-25 04:06:57:353 [WD Proxy]     at Object.onceWrapper (events.js:420:28)
2021-03-25 04:06:57:353 [WD Proxy]     at Socket.emit (events.js:326:22)
2021-03-25 04:06:57:354 [WD Proxy]     at Socket._onTimeout (net.js:483:8)
2021-03-25 04:06:57:354 [WD Proxy]     at listOnTimeout (internal/timers.js:554:17)
2021-03-25 04:06:57:354 [WD Proxy]     at processTimers (internal/timers.js:497:7)
2021-03-25 04:06:57:356 [W3C (7f4121c1)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 480000ms exceeded
2021-03-25 04:06:57:356 [W3C (7f4121c1)]     at UIA2Proxy.command (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
2021-03-25 04:06:57:356 [W3C (7f4121c1)]     at runMicrotasks (<anonymous>)
2021-03-25 04:06:57:357 [W3C (7f4121c1)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-25 04:06:57:359 [HTTP] <-- POST /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/element/5264a6b5-7551-4c60-ae6c-6707a8256da6/value 500 60015 ms - 657

```
After the error is reported, the session is not terminated, and you can still take a screenshot
```log
2021-03-25 04:06:57:366 [HTTP] --> GET /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/screenshot
2021-03-25 04:06:57:366 [HTTP] {}
2021-03-25 04:06:57:367 [W3C (7f4121c1)] Calling AppiumDriver.getScreenshot() with args: ["7f4121c1-5a08-476f-9407-8b36d19d4731"]
2021-03-25 04:06:57:367 [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
2021-03-25 04:06:57:368 [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/0fb5edbf-1fe4-4549-91b7-364bbc14aa5c/screenshot] with no body
2021-03-25 04:06:58:944 [WD Proxy] Got response with status 200: {"sessionId":"0fb5edbf-1fe4-4549-91b7-364bbc14aa5c","value":"iVBORw0KGgoAlLF5SfdzB1P/OyNxdG3eaFv/ybN/++mFseujru\n4EHqpM3huAZiJfXSprevgVhJ...
2021-03-25 04:06:58:953 [W3C (7f4121c1)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAtAAAA4g8AuhBKROwtX7A+z3BcKWKYBVVcg0m7CrSt8UrAv7PD4yzCascZTN\nqxtsanQ24aWea+bXRqCOh8WtfIqxV1/Ke6\nnq1Thp...
2021-03-25 04:06:58:957 [HTTP] <-- GET /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/screenshot 200 1591 ms - 413100
2021-03-25 04:06:58:957 [HTTP] 
2021-03-25 04:06:59:091 [HTTP] --> GET /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/screenshot
2021-03-25 04:06:59:092 [HTTP] {}
2021-03-25 04:06:59:092 [W3C (7f4121c1)] Calling AppiumDriver.getScreenshot() with args: ["7f4121c1-5a08-476f-9407-8b36d19d4731"]
2021-03-25 04:06:59:093 [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
2021-03-25 04:06:59:093 [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/0fb5edbf-1fe4-4549-91b7-364bbc14aa5c/screenshot] with no body

2021-03-25 04:06:59:141 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2021-03-25 04:06:59:142 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.20.2"}}

2021-03-25 04:07:00:935 [WD Proxy] Got response with status 200: {"sessionId":"0fb5edbf-1fe4-4549-91b7-364bbc14aa5c","value":"iVBORwAC2EEEIIIUQcTC3/aax3U1ZSGfagooDZYiY1IwmrzXLIL+bzBdi9ZS+V\nZTU4E+yMGDcUh8vWfPgVhJm0Ra...
2021-03-25 04:07:00:947 [W3C (7f4121c1)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAtAAAAWgCMus2Lf/kPb/59Mbc8fHXcwYO0\nSaveOAdiJe3SqqfPgVhJm0Ra0+jhjK0FUR+zqwoXZyRzfW4aWea+7XSqD+h8XtvAa+W1/Leqjq1T\nR5Cpxl...
2021-03-25 04:07:00:955 [HTTP] <-- GET /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731/screenshot 200 1864 ms - 415216
2021-03-25 04:07:00:955 [HTTP] 
2021-03-25 04:07:01:057 [HTTP] --> DELETE /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731
2021-03-25 04:07:01:057 [HTTP] {}
2021-03-25 04:07:01:057 [W3C (7f4121c1)] Calling AppiumDriver.deleteSession() with args: ["7f4121c1-5a08-476f-9407-8b36d19d4731"]
2021-03-25 04:07:01:058 [BaseDriver] Event 'quitSessionRequested' logged at 1616645221058 (21:07:01 GMT-0700 (Pacific Daylight Time))
2021-03-25 04:07:01:058 [Appium] Removing session 7f4121c1-5a08-476f-9407-8b36d19d4731 from our master session list
2021-03-25 04:07:01:059 [UiAutomator2] Deleting UiAutomator2 session
2021-03-25 04:07:01:059 [UiAutomator2] Deleting UiAutomator2 server session
2021-03-25 04:07:01:059 [WD Proxy] Matched '/' to command name 'deleteSession'
2021-03-25 04:07:01:059 [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/0fb5edbf-1fe4-4549-91b7-364bbc14aa5c] with no body
2021-03-25 04:07:01:089 [WD Proxy] Got response with status 200: {"sessionId":"0fb5edbf-1fe4-4549-91b7-364bbc14aa5c","value":null}
2021-03-25 04:07:01:089 [ADB] Running '/root/platform-tools/adb -P 5037 -s 172.16.16.178:5555 shell am force-stop com.GotoCash'
2021-03-25 04:07:01:248 [Logcat] Stopping logcat capture
2021-03-25 04:07:01:251 [ADB] Removing forwarded port socket connection: 8200 
2021-03-25 04:07:01:251 [ADB] Running '/root/platform-tools/adb -P 5037 -s 172.16.16.178:5555 forward --remove tcp:8200'
2021-03-25 04:07:01:272 [UiAutomator2] Restoring hidden api policy to the device default configuration
2021-03-25 04:07:01:273 [ADB] Running '/root/platform-tools/adb -P 5037 -s 172.16.16.178\:5555 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
2021-03-25 04:07:01:427 [Instrumentation] .
2021-03-25 04:07:01:651 [BaseDriver] Event 'quitSessionFinished' logged at 1616645221650 (21:07:01 GMT-0700 (Pacific Daylight Time))
2021-03-25 04:07:01:651 [W3C (7f4121c1)] Received response: null
2021-03-25 04:07:01:652 [W3C (7f4121c1)] But deleting session, so not returning
2021-03-25 04:07:01:652 [W3C (7f4121c1)] Responding to client with driver.deleteSession() result: null
2021-03-25 04:07:01:654 [HTTP] <-- DELETE /wd/hub/session/7f4121c1-5a08-476f-9407-8b36d19d4731 200 596 ms - 14
```

**Comment by budtmo** [comment]
it is already closed in Appium repository.

**Comment by budtmo** [comment]
it is already closed in Appium repository.
