### ISSUE TITLE
Error building image on ubuntu

### ISSUE THREAD

**Issue by nayibor** [appium/appium-docker-android#137]
Hello,

Thanks for this very useful image.
i found it very useful for beginners whom want to try appium,selenium.

i was having an issue when using ubuntu to build the image.
i got the error below at some point in the installation.

```

**/usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:21
  androidHelpers.getJavaVersion(false).then(function tryInstall (version) {
                 ^
TypeError: androidHelpers.getJavaVersion is not a function
    at doInstall (/usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:21:18)
    at Object.<anonymous> (/usr/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules/appium/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-selendroid-driver@1.13.4 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.13.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-17T23_40_46_019Z-debug.log**

```

i dont know if its got to do with the os version i am running which is Ubuntu 20.04.2 LTS.
i see  some error above about unsupported platform.
Any idea about this

**Comment by nayibor** [comment]
seems it doesnt support this architecture.
will close this.
thanks.
